name: Deploy Jekyll site (no artifacts)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write   # needed to push to gh-pages branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build -d ./_site

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g gh-pages
          gh-pages -d _site -t true -r https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git